export const DEFAULT_SPOTIFY_CALLBACK = 'https://example.com/callback';
export const SPOTIFY_MISSING_CONFIGURATION_ERROR = 'SPOTIFY_MISSING_CONFIGURATION_ERROR';
export const SPOTIFY_AUTH_ERROR = 'SPOTIFY_AUTH_ERROR';
export const SPOTIFY_REFRESH_TOKEN_ERROR = 'SPOTIFY_REFRESH_TOKEN_ERROR';
